/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/app/paper-theme.ts
 * Command: astryx theme build src/app/paper-theme.ts
 * CLI: @astryxdesign/cli@0.6.1
 * Core: @astryxdesign/core@0.6.1
 */

/// <reference path="./yovoice-paper.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const yovoicePaperTheme: DefinedTheme;
