import React from 'react';
import { createRoot } from 'react-dom/client';
import { Theme } from '@astryxdesign/core/theme';
import '@astryxdesign/core/reset.css';
import '@astryxdesign/core/astryx.css';
import { App } from './app/app';
import { yovoicePaperTheme } from './app/yovoice-paper';
import './app/yovoice-paper.css';
import './app/styles.css';
createRoot(document.getElementById('root')!).render(<React.StrictMode><Theme theme={yovoicePaperTheme} mode="light"><App /></Theme></React.StrictMode>);
